io.honeymon.antipang:
  name: Honeymon(by App)
  email: ihoneymon+antipang@gmail.com
  site-url: https://honeymon.io
logging:
  level:
    io.honeymon.boot.antipang: debug
spring:
  pid:
    file: app.pid   # ApplicationPidFileWriter를 사용한다면 이름을 지정가능